data:extend({
  {
    type = "int-setting",
    name = "wiretap-interval-seconds",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 3600,
    order = "a",
  },
  {
    type = "string-setting",
    name = "wiretap-mode",
    setting_type = "runtime-global",
    default_value = "snapshot",
    allowed_values = {"snapshot", "journal", "both"},
    order = "b",
  },
  {
    type = "string-setting",
    name = "wiretap-filename",
    setting_type = "runtime-global",
    default_value = "wiretap/stats.json",
    order = "c",
  },
  {
    type = "string-setting",
    name = "wiretap-journal-filename",
    setting_type = "runtime-global",
    default_value = "wiretap/stats.ndjson",
    order = "d",
  },
  {
    type = "bool-setting",
    name = "wiretap-server-only",
    setting_type = "runtime-global",
    default_value = true,
    order = "e",
  },
  {
    type = "bool-setting",
    name = "wiretap-logistics",
    setting_type = "runtime-global",
    default_value = true,
    order = "f",
  },
  {
    type = "bool-setting",
    name = "wiretap-quality-breakdown",
    setting_type = "runtime-global",
    default_value = false,
    order = "g",
  },
  {
    type = "bool-setting",
    name = "wiretap-power",
    setting_type = "runtime-global",
    default_value = true,
    order = "h",
  },
  {
    type = "bool-setting",
    name = "wiretap-power-breakdown",
    setting_type = "runtime-global",
    default_value = true,
    order = "i",
  },
  {
    type = "bool-setting",
    name = "wiretap-accumulators",
    setting_type = "runtime-global",
    default_value = true,
    order = "j",
  },
  {
    type = "bool-setting",
    name = "wiretap-production",
    setting_type = "runtime-global",
    default_value = true,
    order = "k",
  },
  {
    type = "bool-setting",
    name = "wiretap-science",
    setting_type = "runtime-global",
    default_value = true,
    order = "ka",
  },
  {
    type = "bool-setting",
    name = "wiretap-pollution",
    setting_type = "runtime-global",
    default_value = true,
    order = "l",
  },
})
